apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mydemo-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/ayoub60/mydemo'
    targetRevision: HEAD
    path: k8s
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: mycompany
  syncPolicy:
    automated:
      prune: true
      selfHeal: true

