name: Build & Deploy mydemo

on:
  push:
    branches:
      - main  # ou master selon ton dépôt

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up QEMU for arm64 build
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build JAR with Maven
        run: |
          mvn clean package -DskipTests
          ls -l target/*.jar

      - name: Vérification du contexte de build
        run: |
          echo "Contenu du dossier courant (contexte de build):"
          ls -la
          echo "Contenu de target/ :"
          ls -la target/    

      - name: Build and push Docker image
        run: |
          docker buildx build --platform linux/amd64,linux/arm64 -t ${{ secrets.DOCKER_USERNAME }}/mydemo:latest --push .